Controller Documentation
mixxxdj/manual pull request #122
Opened 2020-08-24 20:55 UTC by Holzhaus

2020-08-29 16:55 UTC, Holzhaus commented
I something like this desired? I don't want to fix all this documentation if it's not desired anyway.

2020-08-31 08:30 UTC, daschuer commented
I think it is desired. But can we effort the maintenance burden? When I correctly remember it is already hard to keep the wiki updated.

2020-09-04 19:34 UTC, Holzhaus commented
> But can we effort the maintenance burden? When I correctly remember it is already hard to keep the wiki updated.

I only added controller that are included in Mixxx. 
I think it makes sense to have documentation for these mappings in the manual as the Wiki page quickly becomes tedious to read when the mapping changes between mixxx versions. We already have some mappings where the wiki page is just a changelog that is completely useless to the end user.

I think adding documentation to the manual opens the possibility to review the documentation properly, too. 

I don't think there's a big maintenance burden, we just need to make sure that anytime a controller mapping is changed the manual page is updated, too.

I suggest the following workflow:
1. Contributor opens PR for a controller mapping
2. We request to add a PR for documentation to the correct branch of this repo
3. We review the documentation and the mapping
4. We merge the mapping only if both the mapping and the documentation are considered ready to merge.

2020-09-04 19:42 UTC, Holzhaus commented
Ok, this is ready to review now. Please have a look.

All obvious formatting issues have been fixed. I removed most of the controller images because I doubt we have the copyright owner's permission and they also don't really add value. Schematic images and images with annotations have been kept.

I also removed all programming related info (MIDI value documentation, `lsusb` output, etc.), because that belongs into the wiki. Changelogs, review links, etc. have been removed, too.

2020-09-07 01:58 UTC, Be-ing commented
How does https://github.com/mixxxdj/mixxx/wiki/Hardware%20compatibility fit into this? Should this be moved into the manual?

2020-09-08 21:09 UTC, Holzhaus commented
> How does https://github.com/mixxxdj/mixxx/wiki/Hardware%20compatibility fit into this? Should this be moved into the manual? I am unsure about that because it lists prices which can change more frequently than we make releases.

I don't think we should put current street prices into the manual. We could use the MSRP or just keep it as simple list (i.e. keep the [current "Controllers" page as-is](https://deploy-preview-122--mixxx-manual.netlify.app/chapters/controllers.html)). The manual is for looking up how your controller works with Mixxx, not for using it as a purchase advice guide.

2020-09-08 22:29 UTC, Be-ing commented
We could make https://github.com/mixxxdj/mixxx/wiki/Hardware%20compatibility link to the manual pages for controllers instead of wiki pages.

2020-09-08 22:57 UTC, Holzhaus commented
Either that or we keep the wiki pages and replace the mapping description with a link to the manual page. Maybe the latter is preferable because some wiki pages contain useful information for mapping developer that I didn't include here (e.g. MIDI message documentation). Also, old Mixxx version include a link to the wiki page, so maybe we shouldn't remove it.

2020-09-08 23:03 UTC, Be-ing commented
Sounds good to me

2020-09-09 00:34 UTC, Holzhaus commented
Ok. Shall we merge?

2020-09-10 20:16 UTC, Holzhaus commented
Merge?

2020-09-12 14:35 UTC, Holzhaus commented
@daschuer Merge?

2020-09-14 10:48 UTC, daschuer commented
The wiki link links to the wiki main page. I guess an average user is pretty lost looking for community mappings. 
I think we need to add some words how to search for them and where. 
The standard GitHub Search feature is not very helpful IMHO.

2020-09-14 11:16 UTC, daschuer requested changes
Many external links are dead. I have checked only the first.

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/behringer_cmd_mm_1.rst
> +.. figure:: ../../_static/controllers/behringer_cmd_mm_1_overview.png
This is a 7,2 MB picture loading slooooow

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/behringer_cmd_studio_4a.rst
> +-  `Manufacturer’s product page <http://www.music-group.com/Categories/Behringer/Computer-Audio/DJ-Controllers/CMD-STUDIO-4a/p/P0809/Features>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/denon_mc6000mk2.rst
> +-  `Manufacturer’s product page <http://denondj.com/products/view/mc6000mk2>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/denon_sc2000.rst
> +-  `Manufacturer’s product page <http://denondj.com/products/view/dn-sc2000>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/gemini_firstmix.rst
> +-  `Manufacturer’s product page <http://geminisound.com/product/firstmix>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/hercules_dj_console_4_mx.rst
> +-  `Manufacturer’s product page <http://www.hercules.com/us/DJ-Music/bdd/p/141/dj-console-4-mx/>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/hercules_dj_console_rmx.rst
> +-  `Manufacturer’s product page <http://www.hercules.com/us/legacy/bdd/p/62/dj-console-rmx/>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/hercules_dj_console_rmx_2.rst
> +-  `Manufacturer’s product page <http://www.hercules.com/us/DJ-Music/bdd/p/193/djconsole-rmx-2/>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/hercules_djcontrol_air.rst
> +-  `Manufacturer’s product page <http://www.hercules.com/fr/legacy/bdd/p/174/djcontrol-air/>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/hercules_djcontrol_compact.rst
> +-  `Manufacturer’s product page <https://www.hercules.com/us/DJ-Music/bdd/p/253/djcontrol-compact/>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/hercules_djcontrol_instinct.rst
> +   -  `DJ Control Instinct S <http://www.hercules.com/us/leisure-controllers/bdd/p/248/djcontrol-instinct-s-series/>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/hercules_djcontrol_instinct.rst
> +   -  `DJ Control Instinct <http://www.hercules.com/us/DJ-Music/bdd/p/187/djcontrol-instinct/>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/hercules_p32_dj.rst
> +-  `Manufacturer’s product page <http://www.hercules.com/uk/advanced-controllers/bdd/p/258/hercules-p32-dj/>`__
dead

2020-09-14 11:16 UTC, daschuer commented on source/chapters/controllers/ion_discover_dj.rst
> +-  `Manufacturer’s product page <http://www.ionaudio.com/products/details/discover-dj>`__
dead

2020-09-14 17:43 UTC, Holzhaus commented on source/chapters/controllers/akai_lpd8.rst
> +   If you own this controller, please consider contributing one.
What contributing guide? Do we have a guide for writing controller mapping documentation?

2020-09-14 17:45 UTC, Holzhaus commented on source/chapters/controllers.rst
> +.. toctree::
AFAIK that's not possible. Sub-toctrees inherit the numbering from their parent, and I see no way to disable this.

2020-09-15 05:16 UTC, daschuer commented on source/chapters/controllers/akai_lpd8.rst
> +   If you own this controller, please consider contributing one.
I think not explicit. Maybe we place two sentences somewhere and link to them here.

2020-09-15 07:13 UTC, daschuer requested changes
Some more broken links

2020-09-15 07:13 UTC, daschuer commented on source/chapters/controllers/reloop_jockey_3_master_edition.rst
> +-  `Manufacturer’s product page <http://www.reloop.com/reloop-jockey-3-me>`__
Dead

2020-09-15 07:13 UTC, daschuer commented on source/chapters/controllers/tascam_us_428.rst
> +-  `Manufacturer’s product page <http://www.tascam.com/products/us-428.html>`__
Dead

2020-09-15 13:58 UTC, Holzhaus commented on source/chapters/controllers/native_instruments_traktor_kontrol_s4_mk2.rst
> +-  `Manufacturer’s product page <https://www.native-instruments.com/en/products/traktor/dj-controllers/traktor-kontrol-s4/>`__
No, it doesn't. Maybe there was a bug on the NI webserver?

2020-09-15 15:18 UTC, Holzhaus commented
Should we rename the "controllers" section to "hardware"? That way we leave the door open for non-controller hardware, e.g. Soundcards, DVS hardware, etc.

2020-09-17 20:38 UTC, Holzhaus commented
I vastly improved the Roland DJ-505 mapping description (didn't bother to do it in the wiki).

2020-09-18 12:53 UTC, daschuer approved these changes
LGTM now. Thank you.

How do we want to proceed?
Delete the wiki pages and redirect to the manual? 

Before, we need to make sure contributors are aware how to improve the controller manual and which part is mandatory when contributing a new mapping.

2020-09-19 20:27 UTC, Holzhaus commented
> LGTM now. Thank you.
> 
> How do we want to proceed?
> Delete the wiki pages and redirect to the manual?

Yes.

> Before, we need to make sure contributors are aware how to improve the controller manual and which part is mandatory when contributing a new mapping.

https://github.com/mixxxdj/mixxx/wiki/Contributing-Mappings#documenting-the-mapping

2020-09-20 18:01 UTC, daschuer commented
Ok, so we can merge now?

2020-09-20 18:02 UTC, Holzhaus commented
Yes.

2020-09-20 18:17 UTC, daschuer commented
Ok, thank you.

2020-09-20 18:17 UTC, merged