Extend/fix mixer documentation
mixxxdj/manual pull request #215
Opened 2020-10-14 13:20 UTC by fiona-byte

2020-10-14 16:14 UTC, ronso0 requested changes

2020-10-14 16:14 UTC, ronso0 commented on source/chapters/user_interface.rst
> +      4. The High Filter Knob
```suggestion
  There are 4 knobs:
      1. Gain
      2. High filter
      3. Mid filter
      4. Low filter
```
This was wrong.
Also when referencing screenshots please describe elements in the same order the appear in the image.

2020-10-14 16:14 UTC, ronso0 commented on source/chapters/user_interface.rst
> +   The mid-position places the filter in a balanced position. This allows the filter to be shared equally by both the left and right sides of the headset.
wrong. EQ knobs affect the volume of certain frequency ranges. Balance is something totally different and balance controls are located only in the Master section of the mixer.
please use Mixxx yourself to test what the controls do and to pick additonal info from the tooltips (see above comment)

2020-10-14 16:14 UTC, ronso0 commented on source/chapters/user_interface.rst
> +  These effects are best heard with the headset as a secondary output.
```suggestion
```

2020-10-14 16:14 UTC, ronso0 commented on source/chapters/user_interface.rst
> +If both decks are playing and the crossfader is in its default center position, then you will hear both decks. Right-clicking on
this change is not necessary IMO.
instead add a section about crossfader assignment switches. those allow you to assign a deck to the left, right or center position of the crossfader.
you find them here:
2 decks
![image](https://user-images.githubusercontent.com/5934199/96016129-b1e5e580-0e48-11eb-9ec7-113234bc1c1e.png)
4 decks 
![image](https://user-images.githubusercontent.com/5934199/96016197-c4601f00-0e48-11eb-8bb1-3a21c0e9c4e6.png)

2020-10-15 09:07 UTC, fiona-byte commented
Alright. I'd make these changes

2020-10-15 10:01 UTC, Holzhaus commented
@fiona-byte you don't need to open a new Pull Request, just `git push` your changes and the PR will be updated.

2020-10-15 15:39 UTC, fiona-byte commented
Alright @Holzhaus . I'd make the necessary changes

2020-10-21 17:32 UTC, ronso0 commented
@fiona-byte Any updates on this? Any issues with `git` we should help with?

2020-10-21 17:34 UTC, ronso0 commented
If you like you can also pick up https://github.com/mixxxdj/manual/issues/238 because it's closely related and rather simple to fix.

2020-10-21 22:06 UTC, ronso0 commented
@fiona-byte 
I just assigned #238 to @ulomau

2020-11-04 15:55 UTC, Holzhaus commented
Is this ready? The review comments are all outdated...

2020-11-04 17:19 UTC, ronso0 commented
Some comments still apply, see https://github.com/mixxxdj/manual/pull/215/files#diff-b69a44a7d04875bdb78b86f9b4c3d69a23de77ad080cd7897f1bce1b19b0588eR881-R883

@fiona-byte Do you plan to finish this?

2020-11-05 06:16 UTC, hannydevelop commented
> @fiona-byte Do you plan to finish this?

Hello @ronso0, @Holzhaus and @fiona-byte should I finish this?

2020-11-05 11:47 UTC, ronso0 commented
Sure, would be appreciated. Some of my first review comments still apply.
I suggest to play with the features you intend to describe and also check the tooltips in the GUI for explanation.

2020-11-05 11:54 UTC, hannydevelop commented
ok

2020-11-06 07:50 UTC, fiona-byte commented
Hi @ronso0 @hannydevelop, you can go ahead and complete it.

2020-11-07 17:04 UTC, hannydevelop commented
> Hi @ronso0 @hannydevelop, you can go ahead and complete it.

Ok @fiona-byte, I'll work on this then.

2020-11-07 20:20 UTC, ronso0 commented
@hannydevelop I suggest to start a new branch and consider the review comments posted here.

2020-11-07 20:21 UTC, closed without merging