fixed broken links
mixxxdj/manual pull request #263
Opened 2020-10-29 12:14 UTC by Goodiec

This pull request is for this issue https://github.com/mixxxdj/manual/issues/240
Kindly review

2020-10-29 14:44 UTC, Holzhaus requested changes
Thanks.

2020-10-29 14:44 UTC, Holzhaus commented on source/chapters/livebroadcasting.rst
>       Intel (macOS 10.8+ 64-bit)
```suggestion
     `LAME <https://lame.sourceforge.io/links.php#Binaries>`_
```

2020-10-29 14:44 UTC, Holzhaus commented on source/chapters/library.rst
> +`build Mixxx from source with m4a/AAC files support <https://github.com/mixxxdj/mixxx/wiki/compiling%20on%20linux#optional-build-with-m4aaac-file-support>`_.
```suggestion
`build Mixxx from source with m4a/AAC files support <https://github.com/mixxxdj/mixxx/wiki/Compiling-On-Linux#user-content-optional-build-with-m4aaac-file-support>`_.
```

Without this, the sphinx link checker still thinks the link is broken.

2020-10-29 14:44 UTC, Holzhaus commented on source/chapters/appendix.rst
> +  * Fix playlist import. `lp:16878282 <https://bugs.launchpad.net/mixxx/+bug/1687828>`__
```suggestion
  * Fix playlist import. `lp:1687828 <https://bugs.launchpad.net/mixxx/+bug/1687828>`__
```

2020-10-29 14:44 UTC, Holzhaus commented on source/chapters/hardware.rst
> +<https://github.com/mixxxdj/mixxx/wiki#controller-mapping-documentation>`_
```suggestion
<https://github.com/mixxxdj/mixxx/wiki#user-content-controller-mapping-documentation>`_
```

2020-10-29 20:44 UTC, Goodiec commented
Done, thank you.

2020-11-02 22:15 UTC, Holzhaus approved these changes
LGTM, thank you.

2020-11-02 22:15 UTC, merged