Describe the relink function better
mixxxdj/manual pull request #287
Opened 2020-11-05 23:51 UTC by Goodiec

This pull request is for issue - https://github.com/mixxxdj/manual/issues/80
Kindly review

2020-11-07 16:25 UTC, ronso0 requested changes

2020-11-07 16:25 UTC, ronso0 commented on source/chapters/preferences.rst
> +  To relink the music directory, go to :menuselection:`Preferences --> Library`,
Let's put this into a new pararaph.
```suggestion

  To relink the music directory, go to :menuselection:`Preferences --> Library`,
```

2020-11-07 16:25 UTC, ronso0 commented on source/chapters/preferences.rst
> +  re-analyzed as the cached analysis is reused, you can confirm this by checking the
```suggestion
  The playlists, crates, history and all track data like cue points, rating, comments etc. are preserved after relinking the library, the tracks are also not
  re-analyzed as the cached analysis is reused. You can confirm this by checking the
```

2020-11-07 16:25 UTC, ronso0 commented on source/chapters/preferences.rst
> +.. note:: It is recommended to take a backup of your Mixxx configuration files when moving or renaming your Mixxx directory.
```suggestion
.. note:: It is recommended to take a backup of your Mixxx configuration files when moving or renaming music directories used in Mixxx.
```

2020-11-08 02:50 UTC, Goodiec commented
@ronso0 I have made the changes, thank you.

2020-11-08 22:35 UTC, ronso0 commented
Thanks, LGTM!

2020-11-08 22:38 UTC, merged