Intro/Outro cues and AutoDJ Mix Mode improvements
mixxxdj/manual pull request #323
Opened 2020-12-10 16:23 UTC by Be-ing

2020-12-10 18:48 UTC, Holzhaus commented on source/chapters/djing_with_mixxx.rst
> +Auto DJ
We should either use "Auto DJ" or "AutoDJ" consistently. I'd prefer the latter.

2020-12-10 21:06 UTC, daschuer commented
No, we are going in circles.
We have decided to use Auto DJ for all visible strings in the GUI.
This should be reflected in the manual.

2020-12-10 21:07 UTC, daschuer requested changes
Please revert the last commit and use Auto DJ.

2021-02-06 12:25 UTC, Holzhaus commented
ping @Be-ing

2021-02-07 00:31 UTC, Be-ing commented
> Please revert the last commit and use Auto DJ.

Okay, I have gone back and done the opposite to change all "AutoDJ" to "Auto DJ".

2021-02-22 21:23 UTC, Be-ing commented
merge?

2021-02-22 22:16 UTC, Holzhaus approved these changes

2021-02-22 22:16 UTC, merged