Changelog Auto-Updater
mixxxdj/manual pull request #422
Opened 2021-08-05 14:10 UTC by Holzhaus

This already allows automating the changelog updates via repository dispatch. I'll open a corresponding PR on the code repo.

To trigger a rebuild automatically, a PAT `REPO_TOKEN` needs to be present in the manual repo's secrets, because the default `GITHUB_TOKEN` doesn't to suffice.

2021-08-05 17:41 UTC, Holzhaus commented
Here's an example:

1. Changelog Workflow: https://github.com/Holzhaus/manual/actions/runs/1101700527 (triggered from command line via cURL)
2. Commit created by the changelog workflow: https://github.com/Holzhaus/manual/commit/080084a00b65ef02b278157295fd52b48a98ebc0 (sorry for the large diff, because the Markdown to RST converter uses a different indentation style)
3. Rebuild (triggered by the changelog workflow): https://github.com/Holzhaus/manual/actions/runs/1101701820

2021-08-07 02:24 UTC, Holzhaus commented
Who can add the repo secret? @daschuer maybe?

2021-08-09 06:39 UTC, daschuer commented
> Who can add the repo secret? @daschuer maybe?

I had just a look in the settings, but I don't know what to do. Do you have some hints?

2021-08-15 11:00 UTC, Holzhaus commented
Ready to merge. Tested on my own repo, here's the commit generated by the bot: https://github.com/Holzhaus/manual/commit/a4b9555f21ae0a6812883a9e3dea55653980b89e

2021-08-16 15:42 UTC, Holzhaus commented
Merge?

![graphics-spongebob-163388](https://user-images.githubusercontent.com/1834516/129590941-f4bf669b-8ded-446f-8ba1-ea387b73acae.gif)

2021-08-18 10:01 UTC, Holzhaus commented
Ping. I suggest to merge this before mixxxdj/mixxx#4210 and mixxxdj/mixxx#4211 so that we can test if it works.

2021-08-18 10:10 UTC, daschuer commented
I think this will be hard to maintain later because of some hidden implications. 
I am not able to point them out, because I have not yet fully understand how it works. 
Would you mind to decorate the changes with some comments to improve the situation?

2021-08-18 10:14 UTC, daschuer commented
This introduces some implications the author of the CHANGLOG.md file should be aware of. 
How can we make it sure that he his aware?

2021-08-18 10:34 UTC, Swiftb0y requested changes

2021-08-18 10:34 UTC, Swiftb0y commented on tools/update_changelog.py
> +        "^# Changelog$",
```suggestion
        r"^#\s*Changelog\s*$",
```
makes it a bit more robust without producing false positives

2021-08-18 11:05 UTC, Holzhaus commented
> I think this will be hard to maintain later because of some hidden implications.
> I am not able to point them out, because I have not yet fully understand how it works.
> Would you mind to decorate the changes with some comments to improve the situation?

I added some explaining comments, however I'm unsure if this is what you meant.

> This introduces some implications the author of the CHANGLOG.md file should be aware of.
> How can we make it sure that he his aware?

The implication is that `CHANGELOG.md` has to be valid markdown. This is not new. Anyway, to enforce valid markdown I opened https://github.com/mixxxdj/mixxx/pull/4222.

2021-08-30 22:29 UTC, Holzhaus commented
Ping.

2021-08-31 06:27 UTC, daschuer commented on tools/update_changelog.py
> +    )
All these sub() calls are putting implications on the Changelog file.
Can we move the link check to the pre-commit hook of the main repro?
Can we remove the Changelog headline hack?
IMHO there is nothing bad about using the same headline everywhere.

2021-09-04 13:31 UTC, daschuer approved these changes
LGTM, thank you.

2021-09-04 13:32 UTC, daschuer commented
@Swiftb0y: merge?

2021-09-04 13:52 UTC, Swiftb0y approved these changes
Sorry, I forgot I had to approve the PR after my suggestions have been incorporated.

2021-09-04 13:53 UTC, Swiftb0y commented
I suggest we make an exception this time and let @Holzhaus merge both PRs himself in the order they require to be merged.

2021-09-04 19:55 UTC, merged

2021-09-04 21:04 UTC, Holzhaus commented
It works: https://github.com/mixxxdj/manual/commit/52c82e0c567927ab98020f8cd576d6c487e37128