Update [Library],focused_widget
mixxxdj/manual pull request #476
Opened 2022-03-17 15:50 UTC by ronso0

updated documentation for https://github.com/mixxxdj/mixxx/pull/4618

2022-03-17 16:06 UTC, ronso0 commented
https://deploy-preview-476--mixxx-manual.netlify.app/chapters/appendix/mixxx_controls.html#control-[Library]-focused_widget

2022-03-17 17:03 UTC, Swiftb0y requested changes
lgtm otherwise

2022-03-17 17:03 UTC, Swiftb0y commented on source/chapters/appendix/mixxx_controls.rst
> +     3         x           Tracks table or root views of library features
We used uppercase X in all other tables.
```suggestion
     1         X           Search bar
     --------  ----------  ------------------------------------------------------------------------------------------------
     2         X           Tree view
     --------  ----------  ------------------------------------------------------------------------------------------------
     3         X           Tracks table or root views of library features
```

2022-03-17 19:30 UTC, ronso0 commented
Comment addessed, and `GoToItem` updated as well.

2022-03-17 21:21 UTC, Swiftb0y approved these changes

2022-03-21 18:48 UTC, ronso0 commented
merge?

2022-03-21 21:25 UTC, Swiftb0y reviewed
Sorry I had a thought shortly after approving but forgot to actually submit the review.

2022-03-21 22:30 UTC, ronso0 commented on source/chapters/appendix/mixxx_controls.rst
> +     ========  ==========  ================================================================================================
The idea is 0 is null/none (self-explaining), and then there is the 1-3 block with writeable widgets from the previous approach. Breaking up that most meaningful sequence of 0-4 doesn't make much sense to me tbh.

2022-03-21 23:37 UTC, Swiftb0y commented on source/chapters/appendix/mixxx_controls.rst
> +     ========  ==========  ================================================================================================
Well, assuming we add more widgets, they will have to be added after the `Unknown` category/slot. Which also does not make much sense semantically. If you think that having 0-4 grouped together makes sense, then I'd propose to shift them up and make `Unknown` the zero slot.

2022-03-21 23:39 UTC, Swiftb0y commented on source/chapters/appendix/mixxx_controls.rst
> +     ========  ==========  ================================================================================================
Having `Unknown` as 0 also makes sense from the POV that its like the `nullptr` when we simply need an implicit fallback value...

To be honest, I'm not super fixated on this issue I just thought I'd mention it. Its fine if you reject it when you don't see the benefit. Saves a little bit of work too.

2022-03-22 14:23 UTC, ronso0 commented on source/chapters/appendix/mixxx_controls.rst
> +     ========  ==========  ================================================================================================
Okay, thanks for your review then.
I just don't see use cases for more concrete _FocusWidget_ enum items:
* there are no (focusable) widgets that need to be considered in scripts, all have dedicated controls already (e.g. spinboxes and effect selectors)
* I doubt we add more focusable widgets to the current skin system
* for a future multi-pane library the enum concept is not suitable and we'd to rework the focus concept anyway

2022-05-21 20:52 UTC, ronso0 commented on source/chapters/appendix/mixxx_controls.rst
> +     ========  ==========  ================================================================================================
:bell:  _ping_ @Swiftb0y ?

2022-05-22 15:24 UTC, Swiftb0y commented on source/chapters/appendix/mixxx_controls.rst
> +     ========  ==========  ================================================================================================
Sorry for neglecting this. Thanks for the ping. I don't have any more arguments to convince you. Though I don't consider "we won't change this anyways" a very foresightful perspective.
I won't die on this hill, and the current state is already implemented, so lets just keep it as is.

2022-05-22 15:24 UTC, Swiftb0y approved these changes

2022-05-23 09:32 UTC, ronso0 commented on source/chapters/appendix/mixxx_controls.rst
> +     ========  ==========  ================================================================================================
> * I doubt we add more focusable widgets to the current skin system
> * for a future multi-pane library the enum concept is not suitable and we'd need to rework the focus concept anyway

Sorry if this sounds arrogant or ignorant, it's just that I don't see that anyone would invest more time into significant additions the current skin engine or work on a multi-pane library.

Also, please take a look at the `getFocusWidget` implementation https://github.com/mixxxdj/mixxx/blob/main/src/library/librarycontrol.cpp#L766. We already fallback to `None` if no Mixxx window has focus or if the main window has no focused widget, and `None` is considered in all library navigation slots.

`[Libary], focused_widget` is in main only and that is still alpha, so if you think we should split `unknown` into known but unaddressed widgets and actually unknown widgets, and change the enum order to put yet unaddressed widgets after the important library widgets... we could still do that.

Anyway, this PR just documents the _current_ implementation so let's merge it.

2022-05-23 12:48 UTC, merged