Fix link to DDJ 400 manual
mixxxdj/manual pull request #523
Opened 2022-11-03 22:15 UTC by daschuer

2022-11-03 22:24 UTC, ronso0 commented
LGTM
Though where are the CI checks?

2022-11-04 09:11 UTC, ronso0 requested changes

2022-11-04 09:11 UTC, ronso0 commented on source/hardware/controllers/pioneer_ddj_400.rst
> +- `Manufacturer's User Manual <https://support.pioneerdj.com/hc/en-us/articles/4404919716761>`__
The links in that page are redundant IMO, all resources are listed in the DDJ400 main support page, except the MIDI messages table and the hardware diagram.

So, let's link to the parent page instead and remove the fixed Firmware link below
```suggestion
- `Manufacturer's Support Page <https://support.pioneerdj.com/hc/en-us/sections/4416577146009-DDJ-400>`__
```

2022-11-04 09:11 UTC, ronso0 commented
https://deploy-preview-523--mixxx-manual.netlify.app/hardware/controllers/pioneer_ddj_400.html

2022-11-04 09:18 UTC, ronso0 commented
and `trailing-whitespace` fails

2023-01-30 18:39 UTC, JoergAtGithub commented
I think this is superseded by #532 and #529 now?

2023-01-30 22:41 UTC, daschuer commented
Oh yes, I forgot about this.

2023-01-30 22:41 UTC, closed without merging