Addresses first half of #530.
mixxxdj/manual pull request #531
Opened 2023-01-17 15:21 UTC by J-Kappes

Added HINT that users can reset the rate and pitch on track load.

2023-01-28 00:08 UTC, JoergAtGithub commented
I wonder, why there are no CI runs for this PR?

2023-01-28 01:04 UTC, ronso0 commented
yeah, that's strange.
@J-Kappes Do you mind rebasing you branch and force-push?
and while you're at it, please reword the commit message to "add HINT that users can reset the rate and pitch on track load" (since that is more meaningful than the current message ; )
Thanks!

2023-01-28 09:24 UTC, J-Kappes commented
> I wonder, why there are no CI runs for this PR?

Maybe because I started this as a draft, idk

2023-01-28 14:59 UTC, Swiftb0y commented
> I wonder, why there are no CI runs for this PR?

IIUC that can happen when the most recent commit is a clean merge commit or if the checks already failed in the feature branch in the repo of the PR author...

2023-01-29 20:35 UTC, ronso0 requested changes

2023-01-29 20:35 UTC, ronso0 commented on source/chapters/user_interface.rst
> +
the indentation has to match the above paragraph = +2 spaces

2023-01-29 20:39 UTC, ronso0 commented
pre-commit fails with
```
fatal: could not read Username for 'https://gitlab.com/': No such device or address
```
:shrug:

2023-01-29 20:45 UTC, JoergAtGithub commented
The fix for the gitlab issue is in https://github.com/mixxxdj/manual/pull/529, but for some reasons this PR fails on CI.

2023-01-30 07:46 UTC, daschuer commented
The Pioneer link is fixed here: https://github.com/mixxxdj/manual/pull/532 the https://web.archive.org links are still OK, probably a temporary issue.

2023-01-30 18:07 UTC, ronso0 commented on source/chapters/user_interface.rst
> +
oh, sorry, my hint was unclear obviously.
Indentation inside the hint block was fine, just the entire block should be at the same i. level as the paragraph above.

2023-01-30 18:09 UTC, ronso0 commented on source/chapters/user_interface.rst
> +
actually, pre-commit would notice that if it wouldn't fail earlier.

2023-01-30 19:23 UTC, JoergAtGithub commented
If you merge in the changes from 2.3 branch, the Sphinx-Linkcheck fails in CI should be solved.

2023-01-31 21:18 UTC, ronso0 approved these changes

2023-01-31 21:18 UTC, ronso0 commented
@JoergAtGithub wanna press merge : )

2023-01-31 21:19 UTC, merged

2023-01-31 21:20 UTC, JoergAtGithub commented
Pressed!