Describe Sync Lock with Dynamic Tempo
mixxxdj/manual pull request #589
Opened 2023-10-10 21:51 UTC by daschuer

2023-10-11 08:10 UTC, ronso0 requested changes
Just some typos/rephrasing

2023-10-11 08:10 UTC, ronso0 commented on source/chapters/djing_with_mixxx.rst
> +create a variable BPM beat grid for all tracks by unchecking :guilabel:`Assume constant tempo`
```suggestion
create variable BPM beat grids for all tracks to be (re)analyzed later on by unchecking :guilabel:`Assume constant tempo`
```

2023-10-11 08:10 UTC, ronso0 commented on source/chapters/djing_with_mixxx.rst
> +When such a track is playing in a Leader deck, the follower decks closely follows the tempo.
```suggestion
When such a track is playing in a Leader deck, the follower decks closely follow the tempo.
```

2023-10-11 08:10 UTC, ronso0 commented on source/chapters/djing_with_mixxx.rst
> +the actual played tempo isn't correctly detected.
```suggestion
the actual played tempo wasn't detected correctly.
```

2023-10-11 08:10 UTC, ronso0 commented on source/chapters/djing_with_mixxx.rst
> +track instedad, click the Leader (Crown) button of its deck.
```suggestion
track instead, click the Leader (Crown) button of its deck.
```

2023-10-11 08:10 UTC, ronso0 commented on source/chapters/djing_with_mixxx.rst
> +The deck becomes than the explicit leader. By another click on the Leader button the
```suggestion
The deck then becomes the explicit leader. Click again on the Leader button and the
```

2023-10-11 08:10 UTC, ronso0 commented on source/chapters/djing_with_mixxx.rst
> +transition and you may pick a dynamic track as a leader by cklick the
```suggestion
transition and you may pick a dynamic track as a leader by clicking the
```

2023-10-11 08:10 UTC, ronso0 commented on source/chapters/djing_with_mixxx.rst
> +A leader plays always the original recorded tempo changes. A follower change its
```suggestion
A leader plays always the original recorded tempo changes. A follower changes its
```

2023-10-11 08:47 UTC, daschuer commented
Thank you.

2023-10-11 20:22 UTC, daschuer commented
OK 2.3 is merge to 2.4, translations are updated and this is rebased on top of all.

2023-10-11 20:56 UTC, ronso0 commented
Cool.
I just tried to enhance the text flow. Even though I think the text is comprehensible I doubt I have a 'naive look' at the text, i.e. put myself into a noob's position.
Someone else should double-check before we merge this.

2023-10-12 05:14 UTC, daschuer commented
@ywwg Can you have a look?

2023-11-06 15:42 UTC, ywwg approved these changes
no notes! Well-described and written.  Thank you.

2023-11-06 20:18 UTC, ronso0 commented
Thanks for your review!

2023-11-06 20:18 UTC, merged