update looping descriptions (no redundant loop cue)
mixxxdj/manual pull request #609
Opened 2024-01-29 13:33 UTC by ronso0

2024-01-29 17:06 UTC, daschuer requested changes
For my understanding the changelog is auto generated from the mixxx repository. I am afraid it will conflict later if we fux the typo here

2024-01-29 17:55 UTC, daschuer commented
I don't understand how this will conflict. How to proceed here? Merge here or waiting for the fix in mixxx?

2024-01-29 19:20 UTC, ronso0 commented
Just merge?

2026-04-14 22:53 UTC, ronso0 commented
_ding, dong?_

2026-04-15 16:02 UTC, daschuer approved these changes
Yes, LGTM

2026-04-15 16:04 UTC, merged